-- Rights metadata is descriptive governance, not legal advice. Every future implementation or adaptation
-- determination remains deferred to an authorized rights/legal reviewer.
-- @statement
INSERT INTO rights_record(
    rights_id, version_id, copyright_holder, license_identifier, rights_statement,
    commercial_use_status, attribution_required, adaptation_permission,
    redistribution_permission, share_alike_required, permissions_route,
    rights_verified_at, rights_evidence_url, rights_review_required
) VALUES
('rights-who-fhs', 'who-fhs-2025', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'Noncommercial copying, redistribution, translation, and adaptation are permitted with attribution and share-alike terms; WHO permission is required for commercial use.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/publications/b/77298', 1),
('rights-who-equip', 'who-equip-2026', 'World Health Organization and United Nations Children''s Fund', 'CC BY-NC-SA 3.0 IGO', 'The official digital-publication record identifies CC BY-NC-SA 3.0 IGO and requires permission for commercial use.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/publications/b/82490', 1),
('rights-who-pm', 'who-pm-plus-v1-1-2018', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'The acquired publication identifies noncommercial reuse and adaptation under CC BY-NC-SA 3.0 IGO; commercial use requires WHO permission.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/about/policies/publishing/copyright', 1),
('rights-who-pm-training', 'who-pm-plus-training-2025', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'Noncommercial copying, redistribution, translation, and adaptation are permitted with attribution and share-alike terms; commercial use requires WHO permission.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/publications/b/78058', 1),
('rights-who-self-help', 'who-self-help-2026', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'The official digital-publication record identifies the noncommercial share-alike license and commercial permission requirement.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/publications/b/82448', 1),
('rights-who-step', 'who-step-by-step-2026', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'The annex belongs to the WHO self-help publication family; commercial adaptation or reproduction remains permission-gated and requires source-specific confirmation.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/about/policies/publishing/copyright', 1),
('rights-who-implementation', 'who-implementation-2024', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'The acquired publication identifies noncommercial reuse and adaptation under CC BY-NC-SA 3.0 IGO; commercial use requires WHO permission.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/about/policies/publishing/copyright', 1),
('rights-who-mhgap-2015', 'who-mhgap-guideline-2015', 'World Health Organization', 'WHO all-rights-reserved publication terms', 'The historical publication predates WHO''s current default open-access practice; reuse and adaptation require source-specific permission review.', 'COPYRIGHTED_REFERENCE_ONLY', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://iris.who.int/server/api/core/bitstreams/6b9d19fe-b732-4065-bd2f-9736f4061a7e/content', 1),
('rights-who-mhgap-2023', 'who-mhgap-guideline-2023', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'Noncommercial copying, redistribution, and adaptation are permitted with attribution and share-alike terms; commercial use requires WHO permission.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/publications/b/70678', 1),
('rights-who-mhgap-ig1', 'who-mhgap-ig-v1-2010', 'World Health Organization', 'WHO all-rights-reserved publication terms', 'The acquired 2010 publication is an all-rights-reserved historical artifact; reproduction, adaptation, or commercial use requires permission review.', 'COPYRIGHTED_REFERENCE_ONLY', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://iris.who.int/server/api/core/bitstreams/750ff48a-1e39-4725-9a43-6e75624ec53e/content', 1),
('rights-who-mhgap-ig2', 'who-mhgap-ig-v2-2016', 'World Health Organization', 'WHO all-rights-reserved publication terms', 'The acquired 2016 second version states all rights reserved and directs reproduction and translation requests to WHO.', 'COPYRIGHTED_REFERENCE_ONLY', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://iris.who.int/server/api/core/bitstreams/6ded7ffd-9d69-493a-b48a-0b3e6250c173/content', 1),
('rights-who-live-life', 'who-live-life-2021', 'World Health Organization', 'CC BY-NC-SA 3.0 IGO', 'Noncommercial reuse and adaptation are permitted with attribution and share-alike terms; commercial use requires WHO permission.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'NONCOMMERCIAL_ONLY', 'NONCOMMERCIAL_ONLY', 1, 'https://www.who.int/about/policies/publishing/copyright', '2026-09-03', 'https://www.who.int/about/policies/publishing/copyright', 1),
('rights-nice-ng222', 'nice-ng222-2026', 'National Institute for Health and Care Excellence', 'NICE notice of rights and UK Open Content Licence', 'International reuse and all AI uses require prior NICE approval and an agreement; ordinary reuse terms do not authorize adapting recommendation wording or structure.', 'LEGAL_REVIEW_REQUIRED', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.nice.org.uk/reusing-our-content', '2026-09-03', 'https://www.nice.org.uk/terms-and-conditions', 1),
('rights-nice-ng225', 'nice-ng225-2025', 'National Institute for Health and Care Excellence', 'NICE notice of rights and UK Open Content Licence', 'International reuse and all AI uses require prior NICE approval and an agreement; third-party material remains excluded from NICE permission.', 'LEGAL_REVIEW_REQUIRED', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.nice.org.uk/reusing-our-content', '2026-09-03', 'https://www.nice.org.uk/terms-and-conditions', 1),
('rights-nimh-toolkit', 'nimh-asq-toolkit-web-2026', 'National Institute of Mental Health', 'United States government public-domain text with NIMH reuse conditions', 'NIMH text is generally public domain, but images may not be reused and reuse must not mislead, imply endorsement, advertise products, or appear to provide specific medical advice.', 'PUBLIC_DOMAIN', 1, 'PERMITTED', 'PERMITTED', 0, 'https://www.nimh.nih.gov/site-info/policies', '2026-09-03', 'https://www.nimh.nih.gov/site-info/policies', 1),
('rights-nimh-asq', 'nimh-asq-tool-2025', 'National Institute of Mental Health', 'United States government public-domain text with NIMH reuse conditions', 'NIMH publication information is generally public domain; image, endorsement, accuracy, and medical-advice appearance restrictions still apply.', 'PUBLIC_DOMAIN', 1, 'PERMITTED', 'PERMITTED', 0, 'https://www.nimh.nih.gov/site-info/policies', '2026-09-03', 'https://www.nimh.nih.gov/site-info/policies', 1),
('rights-va-safety', 'va-safety-planning-web-2026', 'United States Department of Veterans Affairs; possible third-party method rights', 'Rights not established for method-level adaptation', 'Federal web text may be public domain, but the page names a clinical method with third-party provenance; method-level adaptation and commercial use were not established.', 'RIGHTS_UNCLEAR', 1, 'UNCLEAR', 'UNCLEAR', 0, NULL, '2026-09-03', 'https://www.mentalhealth.va.gov/get-help/treatment/ebt.asp', 1),
('rights-samhsa-tip35', 'samhsa-tip35-2019', 'Substance Abuse and Mental Health Services Administration; third-party exceptions', 'SAMHSA public-domain notice with copyrighted-source and fee-distribution exceptions', 'SAMHSA-origin material is public domain except identified third-party content; reproducing or distributing the publication for a fee requires written authorization.', 'COMMERCIAL_PERMISSION_REQUIRED', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.samhsa.gov/about-us/copyright', '2026-09-03', 'https://library.samhsa.gov/sites/default/files/tip-35-pep19-02-01-003.pdf', 1),
('rights-cci-self-help', 'cci-self-help-web-2024', 'State of Western Australia', 'Copyrighted; personal download only absent statutory exception or express permission', 'CCI states that its website materials may be downloaded solely for personal use and may not be published or reproduced without express permission.', 'COPYRIGHTED_REFERENCE_ONLY', 1, 'PERMISSION_REQUIRED', 'PERMISSION_REQUIRED', 0, 'https://www.cci.health.wa.gov.au/Utilities/Copyright-and-Disclaimer', '2026-09-03', 'https://www.cci.health.wa.gov.au/Utilities/Copyright-and-Disclaimer', 1),
('rights-nist-rmf', 'nist-ai-rmf-1-0-2023', 'National Institute of Standards and Technology', 'United States government work; not copyrightable in the United States', 'NIST technical publications are generally public domain in the United States; attribution is requested and third-party or foreign rights must be checked separately.', 'PUBLIC_DOMAIN', 1, 'PERMITTED', 'PERMITTED', 0, NULL, '2026-09-03', 'https://www.nist.gov/nist-research-library/library-faqs', 0),
('rights-nist-genai', 'nist-genai-profile-2024', 'National Institute of Standards and Technology', 'United States government work; not copyrightable in the United States', 'NIST technical publications are generally public domain in the United States; attribution is requested and third-party or foreign rights must be checked separately.', 'PUBLIC_DOMAIN', 1, 'PERMITTED', 'PERMITTED', 0, NULL, '2026-09-03', 'https://www.nist.gov/nist-research-library/library-faqs', 0);
