-- Source-stated or conservatively summarized applicability. software_autonomy_authorized is always false.
-- @statement
INSERT INTO applicability_metadata(
    applicability_id, version_id, population, age_scope, context, setting,
    intended_deliverer, exclusions_or_limits, software_autonomy_authorized
) VALUES
('app-who-fhs', 'who-fhs-2025', 'People receiving psychologically supportive help', 'Adults', 'Foundational helping-skills training', 'Humanitarian and development helping contexts; adaptable training programs', 'Trainers and supervisors preparing human helpers', 'A training resource, not a product authorization or substitute for competence assessment.', 0),
('app-who-equip', 'who-equip-2026', 'Recipients of psychosocial and mental-health care', 'Adults and children according to tool', 'Helper competency assessment', 'Humanitarian and development settings', 'Trainers, supervisors, programs, and assessors', 'Assessment tools have tool-specific populations, administration conditions, and reviewer requirements.', 0),
('app-who-pm', 'who-pm-plus-v1-1-2018', 'People impaired by distress in communities exposed to adversity', 'Adults', 'Individual PM+ intervention', 'Communities exposed to adversity, particularly resource-constrained settings', 'Trained and supervised helpers under the manual''s delivery model', 'Field-trial manual assumptions and exclusion/referral conditions require later clinical review.', 0),
('app-who-pm-training', 'who-pm-plus-training-2025', 'Prospective Individual PM+ helpers', 'Adult intervention recipients; trainees may be adults', 'Training and supervision for Individual PM+', 'Organizations implementing PM+', 'Trainers and organizations preparing human helpers', 'Training completion does not itself establish competence or software suitability.', 0),
('app-who-self-help', 'who-self-help-2026', 'Individuals receiving psychological self-help', 'Source includes intervention-specific age and population limits', 'Guided or self-guided psychological self-help delivery', 'Digital or printed self-help programs and implementation contexts', 'Program implementers, supporters, and intervention users as specified', 'Each featured intervention retains its own scope, support model, exclusions, and escalation assumptions.', 0),
('app-who-step', 'who-step-by-step-2026', 'Step-by-Step intervention users', 'As specified by the annex and implementation context', 'Psychological self-help intervention material', 'Official WHO self-help program delivery', 'Users and support structures specified by the program', 'An annex does not independently establish implementation, safety, or adaptation authority.', 0),
('app-who-implementation', 'who-implementation-2024', 'Potential beneficiaries of manualized interventions', 'Adults, adolescents, and children', 'Service implementation of evidence-based psychological interventions', 'Existing health, social, protection, and education services', 'Managers and people responsible for planning and delivery', 'Implementation/process guidance is not a direct intervention or software-delivery validation.', 0),
('app-who-mhgap-2015', 'who-mhgap-guideline-2015', 'People with mental, neurological, and substance-use disorders', 'Condition-specific', 'Management guidance in primary care', 'Primarily low- and middle-income country non-specialized health services', 'Non-specialist health workers and service planners', 'Superseded evidence authority retained only for history and relationship analysis.', 0),
('app-who-mhgap-2023', 'who-mhgap-guideline-2023', 'People with mental, neurological, and substance-use conditions', 'Condition- and recommendation-specific', 'Evidence recommendations and service scale-up', 'Primary or secondary non-specialized health facilities, especially in low- and middle-income countries', 'Doctors, nurses, other non-specialist health workers, planners, and policy makers', 'Clinical recommendations assume health-system roles and do not confer authority on autonomous software.', 0),
('app-who-mhgap-ig1', 'who-mhgap-ig-v1-2010', 'People with priority mental, neurological, and substance-use conditions', 'Condition-specific', 'Integrated clinical management', 'Non-specialized health settings after local adaptation', 'Health-care providers', 'Superseded procedural guide; not current evidence authority.', 0),
('app-who-mhgap-ig2', 'who-mhgap-ig-v2-2016', 'People with priority mental, neurological, and substance-use conditions', 'Condition-specific', 'Integrated clinical assessment, management, and follow-up', 'Non-specialized health settings', 'Doctors, nurses, other health workers, planners, and managers', 'Older clinical algorithms require comparison with newer evidence and trained-clinician assumptions.', 0),
('app-who-live-life', 'who-live-life-2021', 'National and local populations', 'All ages at population-program level', 'Comprehensive suicide-prevention implementation', 'Countries and communities', 'National or local focal points, governments, and community stakeholders', 'Population implementation guidance is not an individual screening, assessment, or crisis algorithm.', 0),
('app-nice-ng222', 'nice-ng222-2026', 'People with depression', 'Adults aged 18 and over', 'Identification, treatment, management, relapse prevention', 'NHS and related care settings within NICE scope', 'Healthcare professionals and service stakeholders', 'Jurisdiction, clinical-role assumptions, coexisting conditions, and individual recommendations require scoped review.', 0),
('app-nice-ng225', 'nice-ng225-2025', 'People who have self-harmed', 'Children, young people, and adults', 'Assessment, management, and prevention of recurrence', 'Healthcare, social care, education, third sector, and criminal justice sectors', 'Qualified practitioners, commissioners, and relevant service staff', 'Does not cover repetitive stereotypical self-injury; recommendations retain professional-role assumptions.', 0),
('app-nimh-toolkit', 'nimh-asq-toolkit-web-2026', 'Medical patients', 'Ages 8 and above, with youth and adult variants', 'Suicide risk screening implementation and response to positive screens', 'Emergency, inpatient medical/surgical, outpatient, and primary-care medical settings', 'Medical staff; brief safety assessment by a trained clinician', 'No validated screening tool is identified for children under 8; setting must have a positive-screen management plan.', 0),
('app-nimh-asq', 'nimh-asq-tool-2025', 'Medical patients', 'Youth and adults; toolkit specifies ages 8 and above', 'Brief suicide risk screening', 'Medical settings', 'Medical staff with access to the toolkit''s clinical pathway', 'A positive screen requires further trained-clinician assessment; a screen is not a prediction engine.', 0),
('app-va-safety', 'va-safety-planning-web-2026', 'Veterans experiencing suicidal thoughts or behaviors', 'Adults in VA care', 'Collaborative safety planning', 'Veterans Health Administration treatment context', 'A patient working with a provider', 'Public description is not a standalone protocol and may include third-party method rights.', 0),
('app-samhsa-tip35', 'samhsa-tip35-2019', 'People receiving substance-use disorder treatment', 'Primarily adults; chapter-specific scope applies', 'Motivational interventions within substance-use treatment', 'Treatment programs and clinical services', 'Clinicians and treatment-program staff', 'Not a substitute for individualized care; third-party sources and population generalization require review.', 0),
('app-cci-self-help', 'cci-self-help-web-2024', 'People seeking information about mental-health difficulties', 'Primarily adults; domain resources vary', 'Self-help information, workbooks, worksheets, and clinician-supported use', 'Personal self-help or use alongside qualified care', 'Individuals and, for some resources, therapists', 'CCI expressly states the resources are not a substitute for diagnosis or treatment by a qualified professional.', 0),
('app-nist-rmf', 'nist-ai-rmf-1-0-2023', 'Organizations designing, developing, deploying, or using AI systems', 'Not clinical or age-specific', 'Voluntary AI risk management', 'Cross-sector AI lifecycle', 'Organizations and AI risk-management stakeholders', 'Non-sector-specific engineering governance; it supplies no clinical recommendation.', 0),
('app-nist-genai', 'nist-genai-profile-2024', 'Organizations working with generative AI', 'Not clinical or age-specific', 'Generative-AI risk management', 'Cross-sector AI lifecycle', 'Framework users and AI risk-management stakeholders', 'A companion profile, not a clinical standard, model approval, or product certification.', 0);
