-- Additional official web locators used for precise section addressing.
-- @statement
INSERT INTO source_locator(locator_id, version_id, locator_kind, official_url, retrieved_at, media_type, locator_notes) VALUES
('loc-nice-ng222-surveillance', 'nice-ng222-2026', 'OFFICIAL_SURVEILLANCE_RECORD', 'https://www.nice.org.uk/guidance/ng222', '2026-09-03', 'text/html', 'Overview records last review 2026-01-30 and no recommendation update.'),
('loc-nice-ng225-update', 'nice-ng225-2025', 'OFFICIAL_SURVEILLANCE_RECORD', 'https://www.nice.org.uk/guidance/ng225/chapter/Update-information', '2026-09-03', 'text/html', 'August 2024 presentational simplification.'),
('loc-nice-ng225-recommendations', 'nice-ng225-2025', 'OFFICIAL_WEB_RESOURCE', 'https://www.nice.org.uk/guidance/ng225/chapter/Recommendations', '2026-09-03', 'text/html', 'Numbered recommendations.'),
('loc-nimh-adult-toolkit', 'nimh-asq-toolkit-web-2026', 'OFFICIAL_WEB_RESOURCE', 'https://www.nimh.nih.gov/research/research-conducted-at-nimh/asq-toolkit-materials/adults-asq-toolkit', '2026-09-03', 'text/html', 'Adult setting-specific pathways and assessment guides.'),
('loc-cci-depression', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Depression', '2026-09-03', 'text/html', 'Depression resource page; last updated 2019-10-28.'),
('loc-cci-anxiety', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Anxiety', '2026-09-03', 'text/html', 'Anxiety resource page; last updated 2025-07-09.'),
('loc-cci-worry', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Worry-and-Rumination', '2026-09-03', 'text/html', 'Worry and rumination resource page; last updated 2023-07-10.'),
('loc-cci-social-anxiety', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Social-Anxiety', '2026-09-03', 'text/html', 'Social anxiety resource page; last updated 2021-02-03.'),
('loc-cci-panic', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Panic', '2026-09-03', 'text/html', 'Panic resource page; official site announced revised modules 2026-03-09.'),
('loc-cci-self-esteem', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Self-Esteem', '2026-09-03', 'text/html', 'Self-esteem resource page; last updated 2025-04-09.'),
('loc-cci-perfectionism', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Perfectionism', '2026-09-03', 'text/html', 'Perfectionism resource page; last updated 2019-10-24.'),
('loc-cci-procrastination', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Procrastination', '2026-09-03', 'text/html', 'Procrastination resource page; last updated 2025-04-09.'),
('loc-cci-distress', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Tolerating-Distress', '2026-09-03', 'text/html', 'Tolerating distress resource page; last updated 2019-07-15.'),
('loc-cci-health-anxiety', 'cci-self-help-web-2024', 'OFFICIAL_WEB_RESOURCE', 'https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Health-Anxiety', '2026-09-03', 'text/html', 'Health anxiety resource page; last updated 2020-04-15.');
-- @statement
INSERT INTO source_section(section_id, version_id, locator_id, location_type, location_value, subject_label, location_notes) VALUES
('section-fhs-overview', 'who-fhs-2025', 'loc-who-fhs-page', 'WEB_HEADING', 'Overview', 'Foundational helping competency framework', 'Official overview identifies the manual''s competency-based training purpose; the artifact describes 15 competencies.'),
('section-equip-overview', 'who-equip-2026', 'loc-who-equip-page', 'WEB_HEADING', 'Overview', 'Competency assessment tools', 'Tool implementation is intentionally deferred.'),
('section-pm-manual', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'CHAPTER', 'Manual-level procedure', 'Individual PM+ procedure and boundaries', 'Exact stages are not extracted in CT-V2-01.'),
('section-pm-training-part-a', 'who-pm-plus-training-2025', 'artifact-who-pm-training', 'SECTION', 'Part A', 'Implementation, training, supervision, and competency preparation', 'Candidate implementation subject only.'),
('section-pm-training-part-b', 'who-pm-plus-training-2025', 'artifact-who-pm-training', 'SECTION', 'Part B', 'Detailed training delivery', 'Candidate training subject only.'),
('section-self-help-family', 'who-self-help-2026', 'artifact-who-self-help', 'SECTION', 'Intervention delivery manual', 'Guided and self-guided delivery conditions', 'No scripts or exercises are stored.'),
('section-step-annex', 'who-step-by-step-2026', 'artifact-who-step', 'ANNEX', 'B09738', 'Step-by-Step intervention material', 'No intervention content is reproduced.'),
('section-implementation-five-steps', 'who-implementation-2024', 'loc-who-implementation-page', 'WEB_HEADING', 'Overview', 'Five implementation areas', 'Planning, contextual adaptation, workforce, beneficiary support, and monitoring are recorded as a subject, not runtime concepts.'),
('section-mhgap-2015-scope', 'who-mhgap-guideline-2015', 'artifact-who-mhgap-2015', 'CHAPTER', 'Guideline update', '2015 recommendation set', 'Superseded evidence location.'),
('section-mhgap-2023-scope', 'who-mhgap-guideline-2023', 'artifact-who-mhgap-2023', 'SECTION', '1.4 Scope of the guideline', 'Current mhGAP evidence scope and update identity', 'The publication identifies the earlier documents it updates.'),
('section-mhgap-ig1-algorithms', 'who-mhgap-ig-v1-2010', 'artifact-who-mhgap-ig1', 'CHAPTER', 'Integrated management protocols', 'Superseded clinical decision procedures', 'Historical location only.'),
('section-mhgap-ig2-algorithms', 'who-mhgap-ig-v2-2016', 'artifact-who-mhgap-ig2', 'CHAPTER', 'Integrated management algorithms', 'Procedural clinical decision structure', 'Requires later adjudication against current evidence.'),
('section-live-life-overview', 'who-live-life-2021', 'loc-who-live-life-page', 'WEB_HEADING', 'Overview', 'Population-level suicide-prevention implementation', 'Not an individual decision pathway.'),
('section-ng222-treatment-options', 'nice-ng222-2026', 'artifact-nice-ng222', 'RECOMMENDATION', '1.5.2-1.5.3', 'Treatment options and negative guidance', 'Exact numbered location retained without reproducing recommendation text in the corpus.'),
('section-ng225-risk-tools', 'nice-ng225-2025', 'loc-nice-ng225-recommendations', 'RECOMMENDATION', '1.6.1-1.6.4', 'Negative guidance on prediction and global risk stratification', 'High-priority later safety-architecture subject; no logic implemented.'),
('section-ng225-assessment-focus', 'nice-ng225-2025', 'loc-nice-ng225-recommendations', 'RECOMMENDATION', '1.6.5-1.6.6', 'Needs, safety, and professional risk formulation', 'Retains the professional-role boundary.'),
('section-nimh-toolkit-positive', 'nimh-asq-toolkit-web-2026', 'loc-nimh-toolkit-page', 'WEB_HEADING', 'What happens if patients screen positive?', 'Trained-clinician assessment after a positive screen', 'Prevents treatment of the screen as a complete decision system.'),
('section-nimh-adult-pathways', 'nimh-asq-toolkit-web-2026', 'loc-nimh-adult-toolkit', 'WEB_HEADING', 'Downloads and setting-specific pathways', 'Adult medical-setting clinical pathways', 'Pathway use is not authorized.'),
('section-nimh-asq-tool', 'nimh-asq-tool-2025', 'artifact-nimh-asq', 'TOOL', 'ASQ screening tool', 'Brief suicide risk screen', 'Questions and scoring are not reproduced in tracked records.'),
('section-va-safety-plan', 'va-safety-planning-web-2026', 'loc-va-safety-page', 'WEB_HEADING', 'Safety Planning (SP)', 'Collaborative provider-led safety planning', 'Third-party method rights remain unresolved.'),
('section-tip35-ch3', 'samhsa-tip35-2019', 'artifact-samhsa-tip35', 'CHAPTER', '3', 'Motivational Interviewing as a counseling style', 'Method analysis is deferred.'),
('section-tip35-public-domain', 'samhsa-tip35-2019', 'artifact-samhsa-tip35', 'SECTION', 'Publication Information: Public Domain Notice', 'SAMHSA and third-party rights boundary', 'Rights evidence location.'),
('section-cci-depression', 'cci-self-help-web-2024', 'loc-cci-depression', 'WEB_HEADING', 'Workbook - Back from the Bluez', 'Depression self-help materials', 'Metadata only; no workbook copied.'),
('section-cci-anxiety', 'cci-self-help-web-2024', 'loc-cci-anxiety', 'WEB_HEADING', 'Information sheets and worksheets', 'Anxiety CBT materials', 'Metadata only; no worksheet copied.'),
('section-cci-worry', 'cci-self-help-web-2024', 'loc-cci-worry', 'WEB_HEADING', 'Workbook - What? Me Worry?', 'Worry and rumination materials', 'Metadata only; no workbook copied.'),
('section-cci-social', 'cci-self-help-web-2024', 'loc-cci-social-anxiety', 'WEB_HEADING', 'Workbook - Stepping out of Social Anxiety', 'Social anxiety materials', 'Metadata only; no workbook copied.'),
('section-cci-panic', 'cci-self-help-web-2024', 'loc-cci-panic', 'WEB_HEADING', 'Workbook - When Panic Attacks', 'Panic materials', 'Metadata only; no workbook copied.'),
('section-cci-esteem', 'cci-self-help-web-2024', 'loc-cci-self-esteem', 'WEB_HEADING', 'Workbook - Improving Self-Esteem', 'Self-esteem materials', 'Metadata only; no workbook copied.'),
('section-cci-perfectionism', 'cci-self-help-web-2024', 'loc-cci-perfectionism', 'WEB_HEADING', 'Workbook - Perfectionism in Perspective', 'Perfectionism materials', 'Metadata only; no workbook copied.'),
('section-cci-procrastination', 'cci-self-help-web-2024', 'loc-cci-procrastination', 'WEB_HEADING', 'Workbook - Put Off Procrastinating', 'Procrastination materials', 'Metadata only; no workbook copied.'),
('section-cci-distress', 'cci-self-help-web-2024', 'loc-cci-distress', 'WEB_HEADING', 'Workbook - Facing Your Feelings', 'Distress-tolerance materials', 'Metadata only; no workbook copied.'),
('section-cci-health-anxiety', 'cci-self-help-web-2024', 'loc-cci-health-anxiety', 'WEB_HEADING', 'Workbook - Helping Health Anxiety', 'Health-anxiety materials', 'Metadata only; no workbook copied.'),
('section-nist-rmf-core', 'nist-ai-rmf-1-0-2023', 'artifact-nist-rmf', 'SECTION', 'AI RMF Core', 'Govern, Map, Measure, and Manage engineering functions', 'Engineering governance only.'),
('section-nist-genai-risks', 'nist-genai-profile-2024', 'artifact-nist-genai', 'SECTION', '2', 'Generative AI risks', 'Engineering governance only.'),
('section-nist-genai-actions', 'nist-genai-profile-2024', 'artifact-nist-genai', 'SECTION', '3', 'Suggested generative-AI risk-management actions', 'Engineering governance only.');
-- @statement
INSERT INTO candidate_subject(candidate_id, section_id, subject_summary, earliest_authorized_phase) VALUES
('candidate-fhs-framework', 'section-fhs-overview', 'Analyze the source''s observable foundational-helping competency coverage without importing its vocabulary automatically.', 'CT-V2-02'),
('candidate-equip-assessment', 'section-equip-overview', 'Analyze competency-assessment addressability and future qualification applicability.', 'CT-V2-02'),
('candidate-pm-procedure', 'section-pm-manual', 'Analyze PM+ scope, procedure, contraindications, and delivery assumptions.', 'CT-V2-02'),
('candidate-self-help-delivery', 'section-self-help-family', 'Analyze guided and self-guided delivery assumptions for a mobile context.', 'CT-V2-02'),
('candidate-implementation-process', 'section-implementation-five-steps', 'Analyze implementation-governance concepts without converting them to therapeutic behavior.', 'CT-V2-02'),
('candidate-mhgap-currency', 'section-mhgap-2023-scope', 'Compare current evidence with older procedural references before any abstraction.', 'CT-V2-02'),
('candidate-ng225-negative-guidance', 'section-ng225-risk-tools', 'Analyze explicit negative guidance relevant to later safety architecture.', 'CT-V2-02'),
('candidate-asq-boundary', 'section-nimh-toolkit-positive', 'Analyze screening-versus-assessment boundaries and trained-clinician assumptions.', 'CT-V2-02'),
('candidate-mi-method', 'section-tip35-ch3', 'Analyze motivational-method source scope and separate SAMHSA synthesis from primary copyrighted MI works.', 'CT-V2-02'),
('candidate-cci-domains', 'section-cci-anxiety', 'Analyze CCI domain coverage and rights constraints without importing worksheets.', 'CT-V2-02'),
('candidate-genai-governance', 'section-nist-genai-actions', 'Consider later non-clinical renderer and qualification governance.', 'LATER');
