-- Exact source locations inspected for CT-V2-03 rule derivation.
-- These records add addressability only; they do not grant rule or runtime authority.
-- @statement
INSERT INTO source_section(section_id, version_id, locator_id, location_type, location_value, subject_label, location_notes) VALUES
('section-fhs-verbal-communication', 'who-fhs-2025', 'artifact-who-fhs', 'PAGE_RANGE', 'Module 1, Verbal communication, publication pp. 27-31; PDF pp. 38-42', 'Helpful and unhelpful verbal communication', 'Exact location inspected for open questions, summaries, reflective statements, and avoidance of interrupting, leading, corrective, or accusatory language.'),
('section-fhs-collaborative-goals', 'who-fhs-2025', 'artifact-who-fhs', 'PAGE_RANGE', 'Module 8, Collaborative goal-setting, publication pp. 118-120; PDF pp. 129-131', 'Collaborative goals and user expectations', 'Exact location inspected for asking about goals and avoiding forced, misleading, or unrealistic goals.'),
('section-fhs-eliciting-feedback', 'who-fhs-2025', 'artifact-who-fhs', 'PAGE_RANGE', 'Module 8, Eliciting feedback, publication pp. 126-127; PDF pp. 137-138', 'Checking understanding and inviting correction', 'Exact location inspected for asking for feedback, clarifying, summarizing, and checking an interpretation.'),
('section-pm-helper-reluctance', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 3, publication pp. 26-27; PDF pp. 28-29', 'Respect for reluctance or refusal to continue a topic', 'Exact location inspected for the human-helper instruction not to pressure a reluctant client and to respect refusal.'),
('section-pm-advice-boundary', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE', 'Chapter 3, Giving advice, publication p. 24; PDF p. 26', 'General boundary against direct advice', 'Exact location inspected for the distinction between direct advice and supporting a client to consider their own response; PM+ exceptions are not imported.'),
('section-pm-managing-problems', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 7, Managing Problems, publication pp. 46-51; PDF pp. 48-53', 'Manageable practical problems, options, plan, and review', 'Exact location inspected for the seven-step structure. CT-V2-03 abstracts only qualification behavior and imports no text, script, assessment, case, or worksheet.'),
('section-pm-problem-definition', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 7, Managing Problems steps 1-3, publication pp. 46-49; PDF pp. 48-51', 'Problem listing, influenceability, selection, and definition', 'Exact location inspected for the opening problem-definition portion of the procedure.'),
('section-pm-option-generation', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 7, Managing Problems steps 4-5, publication pp. 49-51; PDF pp. 51-53', 'Possible and helpful options', 'Exact location inspected for generating possible options and choosing helpful options.'),
('section-pm-action-plan', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 7, Managing Problems step 6, publication pp. 50-51; PDF pp. 52-53', 'Bounded action planning', 'Exact location inspected for breaking a chosen option into a specific plan.'),
('section-pm-outcome-review', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE', 'Chapter 7, Managing Problems step 7, publication p. 51; PDF p. 53', 'Review of attempted plan', 'Exact location inspected for reviewing what occurred and reconsidering next work.'),
('section-pm-delivery-assumptions', 'who-pm-plus-v1-1-2018', 'artifact-who-pm', 'PAGE_RANGE', 'Chapter 1, publication pp. 8-12; PDF pp. 10-14', 'PM+ scope, training, practice, and supervision assumptions', 'Exact location inspected to preserve the adult adversity-context scope and human-helper training, supervised practice, and support assumptions.');
